#Requires -Version 5.1
<#
.SYNOPSIS
  Merge hand-written briefs into the journal without an API run.
.DESCRIPTION
  The AI desk needs API credits. This is the manual path: write briefs into a JSON
  file (same shape the desk emits) and merge them here. Countries already in the
  state file keep their stories unless the new file overrides them.

  Writes BOTH data/briefs-state.json (the merge memory) and data/briefs.js (what
  the site loads). Editing briefs.js alone would work until the next API run, which
  rebuilds from the state file and would silently drop the hand-written countries.
.USAGE
  powershell -ExecutionPolicy Bypass -File scripts/add-briefs.ps1
  powershell -ExecutionPolicy Bypass -File scripts/add-briefs.ps1 -InFile data/manual-briefs.json
.NOTES
  Run scripts/validate-briefs.ps1 afterwards; it applies the same publication gate
  the daily Action uses.
#>
param(
  [string]$InFile = 'data/manual-briefs.json'
)

$ErrorActionPreference = 'Stop'
$root      = Split-Path $PSScriptRoot -Parent
$statePath = Join-Path $root 'data\briefs-state.json'
$outPath   = Join-Path $root 'data\briefs.js'
$inPath    = if ([IO.Path]::IsPathRooted($InFile)) { $InFile } else { Join-Path $root $InFile }

if (-not (Test-Path $inPath)) { Write-Host "[add] input not found: $inPath" -ForegroundColor Red; exit 1 }
$incoming = [IO.File]::ReadAllText($inPath, [Text.Encoding]::UTF8) | ConvertFrom-Json

$generated = (Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ')
$byCountry = [ordered]@{}
$dates     = [ordered]@{}
$markets   = [ordered]@{}

# Start from existing state so nothing already published is lost.
if (Test-Path $statePath) {
  $prev = [IO.File]::ReadAllText($statePath, [Text.Encoding]::UTF8) | ConvertFrom-Json
  if ($prev.byCountry) { foreach ($p in $prev.byCountry.PSObject.Properties) { $byCountry[$p.Name] = $p.Value } }
  if ($prev.markets)   { foreach ($p in $prev.markets.PSObject.Properties)   { $markets[$p.Name]   = $p.Value } }
  if ($prev.dates)     { foreach ($p in $prev.dates.PSObject.Properties)     { $dates[$p.Name]     = $p.Value } }
}

$added = 0
$stories = 0
foreach ($p in $incoming.PSObject.Properties) {
  $code = $p.Name
  $list = @($p.Value | Where-Object { $_.headline -and $_.body })
  if (-not $list.Count) { Write-Host "  skip $code (no usable briefs)" -ForegroundColor DarkYellow; continue }
  foreach ($b in $list) {
    foreach ($s in @($b.sources)) {
      if ($s -and $s.url -and $s.url -notmatch '^https?://') {
        Write-Host "[add] FAIL $code has a non-http source URL: $($s.url)" -ForegroundColor Red
        exit 1
      }
    }
  }
  $byCountry[$code] = $list
  $dates[$code] = $generated
  $added++
  $stories += $list.Count
  Write-Host ("  {0}  {1} briefs" -f $code, $list.Count) -ForegroundColor Green
}

if ($added -eq 0) { Write-Host '[add] nothing to merge' -ForegroundColor Red; exit 1 }

function ConvertTo-JsBlock($obj) {
  $json = $obj | ConvertTo-Json -Depth 10
  if ($obj.Count -le 1) { $json = "{`n$($json.Trim('{','}'))`n}" }
  return $json
}

$payload = "// Auto-generated by scripts/add-briefs.ps1 - manually merged briefs.`r`n" +
           "// Generated: $generated`r`n" +
           "window.UNITED_AFRICA_BRIEFS = { generated: '$generated', dates: $(ConvertTo-JsBlock $dates), byCountry: $(ConvertTo-JsBlock $byCountry), markets: $(ConvertTo-JsBlock $markets) };`r`n"
[IO.File]::WriteAllText($outPath, $payload, (New-Object Text.UTF8Encoding($false)))

$state = [ordered]@{ generated = $generated; dates = $dates; byCountry = $byCountry; markets = $markets }
[IO.File]::WriteAllText($statePath, ($state | ConvertTo-Json -Depth 10), (New-Object Text.UTF8Encoding($false)))

# --- archive -----------------------------------------------------------------
# A journal keeps a record. build-briefs.ps1 used to write this, and when the desk
# moved to the fetch/write pipeline nothing took the job over: the newest archived
# edition was 2026-08-05 while the live paper had been rebuilt many times since, so
# the wire's "Past editions" picker was quietly frozen and the workflow was committing
# a directory that nothing wrote to.
$day = (Get-Date).ToUniversalTime().ToString('yyyy-MM-dd')
$archiveDir = Join-Path $root 'data\archive'
if (-not (Test-Path $archiveDir)) { New-Item -ItemType Directory -Path $archiveDir | Out-Null }

$archPayload = "// The African Street Journal - archived edition $day (auto-generated).`r`n" +
               "window.__ASJ_ARCHIVE_DAY = { date: '$day', generated: '$generated', byCountry: $(ConvertTo-JsBlock $byCountry), markets: $(ConvertTo-JsBlock $markets) };`r`n"
[IO.File]::WriteAllText((Join-Path $archiveDir "$day.js"), $archPayload, (New-Object Text.UTF8Encoding($false)))

# Rebuild the index from what is actually on disk rather than appending, so a deleted
# edition cannot leave a dangling entry the picker would 404 on.
$editions = @(Get-ChildItem $archiveDir -Filter '*.js' |
              Where-Object { $_.BaseName -match '^\d{4}-\d{2}-\d{2}$' } |
              ForEach-Object { $_.BaseName } | Sort-Object -Descending)
$indexPayload = "window.UNITED_AFRICA_ARCHIVE_INDEX = $($editions | ConvertTo-Json -Compress);`r`n"
if ($editions.Count -eq 1) { $indexPayload = "window.UNITED_AFRICA_ARCHIVE_INDEX = [`"$($editions[0])`"];`r`n" }
[IO.File]::WriteAllText((Join-Path $archiveDir 'index.js'), $indexPayload, (New-Object Text.UTF8Encoding($false)))

Write-Host "[add] merged $stories briefs across $added countries; $($byCountry.Count) countries now in data/briefs.js" -ForegroundColor Green
Write-Host "[add] archived edition $day ($($editions.Count) editions on file)" -ForegroundColor Green
