#Requires -Version 5.1
<#
.SYNOPSIS
  Re-emit data/briefs.js (and today's archive) from data/briefs-state.json without
  running the model.
.DESCRIPTION
  The state file holds everything the desk knows; briefs.js is a derived, reader-sized
  view of it. When the shipping format changes - a field dropped, prose stored once
  instead of twice - the live payload is stale until the next nightly run, and waiting
  a night to see a format change land is a slow way to find out it was wrong.

  This regenerates the derived files from the record. It reads no feeds, calls no API,
  and costs nothing. It cannot invent stories: if the state file does not have it,
  neither does the payload.
.USAGE
  powershell -ExecutionPolicy Bypass -File scripts/rebuild-briefs-payload.ps1
#>
param()

$ErrorActionPreference = 'Stop'
$root = Split-Path $PSScriptRoot -Parent
. (Join-Path $PSScriptRoot 'story-shape.ps1')

$statePath = Join-Path $root 'data\briefs-state.json'
$outPath   = Join-Path $root 'data\briefs.js'
if (-not (Test-Path $statePath)) { Write-Host '[rebuild] no data/briefs-state.json' -ForegroundColor Red; exit 1 }

$state = [IO.File]::ReadAllText($statePath, [Text.Encoding]::UTF8) | ConvertFrom-Json
$generated = [string]$state.generated
if ($state.generated -is [datetime]) { $generated = $state.generated.ToString('yyyy-MM-ddTHH:mm:sszzz') }
$day = Get-IsoDay $state.generated
if (-not $day) { Write-Host '[rebuild] state file has no usable generated stamp' -ForegroundColor Red; exit 1 }

function ConvertTo-JsBlock($obj) {
  $json = $obj | ConvertTo-Json -Depth 10
  if ($obj.Count -le 1) { $json = "{`n$($json.Trim('{','}'))`n}" }
  return $json
}

# A fresh market file overrides whatever the state carried forward, exactly as the merge
# does. Markets have their own workflow and their own cadence - the prices should not
# have to wait for a model run to reach the page.
$markets = $state.markets
$marketsPath = Join-Path $root 'data\markets.json'
if (Test-Path $marketsPath) {
  $live = [IO.File]::ReadAllText($marketsPath, [Text.Encoding]::UTF8) | ConvertFrom-Json
  $merged = [ordered]@{}
  foreach ($p in $state.markets.PSObject.Properties) { $merged[[string]$p.Name] = $p.Value }
  $refreshed = 0
  foreach ($p in $live.PSObject.Properties) { $merged[[string]$p.Name] = $p.Value; $refreshed++ }
  $markets = $merged
  if ($refreshed) { Write-Host "[rebuild] refreshed markets for $refreshed countries from data/markets.json" -ForegroundColor Green }
}

$split = Split-ShippableByCountry $state.byCountry
$shipBy = $split.index
$fullBy = $split.full
$countries = @($shipBy.Keys).Count
$stories = 0
foreach ($k in $shipBy.Keys) { $stories += @($shipBy[$k]).Count }

$payload = "// Auto-generated by scripts/rebuild-briefs-payload.ps1 from data/briefs-state.json.`r`n" +
           "// Generated: $generated`r`n" +
           "// INDEX ONLY - headlines, deks, meta and lens scores. The prose lives in`r`n" +
           "// data/briefs-full.js, which app.js loads after first paint. This file is what`r`n" +
           "// the first screen needs; that one is what an opened story needs.`r`n" +
           "window.UNITED_AFRICA_BRIEFS = { generated: '$generated', dates: $(ConvertTo-JsBlock $state.dates), byCountry: $(ConvertTo-CountryJsBlock $shipBy), markets: $(ConvertTo-JsBlock $markets) };`r`n"
[IO.File]::WriteAllText($outPath, $payload, (New-Object Text.UTF8Encoding($false)))

$fullPath = Join-Path $root 'data\briefs-full.js'
$fullPayload = "// Auto-generated by scripts/rebuild-briefs-payload.ps1 - the deferred half.`r`n" +
               "// Paragraphs, why lines, lens explanations and source URLs, keyed by articleId.`r`n" +
               "// Never render-blocking: app.js loads this once the page is already up.`r`n" +
               "window.UNITED_AFRICA_BRIEFS_FULL = { generated: '$generated', byCountry: $(ConvertTo-CountryJsBlock $fullBy) };`r`n"
[IO.File]::WriteAllText($fullPath, $fullPayload, (New-Object Text.UTF8Encoding($false)))

$archiveDir = Join-Path $root 'data\archive'
$archPath = Join-Path $archiveDir "$day.js"
if (Test-Path $archPath) {
  $archPayload = "// The African Street Journal - archived edition $day (auto-generated).`r`n" +
                 "window.__ASJ_ARCHIVE_DAY = { date: '$day', generated: '$generated', byCountry: $(ConvertTo-CountryJsBlock (ConvertTo-ShippableByCountry $state.byCountry)), markets: $(ConvertTo-JsBlock $markets) };`r`n"
  [IO.File]::WriteAllText($archPath, $archPayload, (New-Object Text.UTF8Encoding($false)))
  Write-Host "[rebuild] archive $day.js re-emitted" -ForegroundColor DarkGray
}

$kb = [math]::Round((Get-Item $outPath).Length / 1KB)
Write-Host "[rebuild] $stories stories across $countries countries -> data/briefs.js ($kb KB)" -ForegroundColor Green
exit 0
