#Requires -Version 5.1
<#
.SYNOPSIS
  Splits the compiled data/app-data.js into a small data/app-core.js (landing map +
  World Bank economy layer) plus one lazy chunk per country in data/countries/<id>.js
  (detailed outline + GIS). index.html loads app-core.js up front and fetches a
  country's chunk the moment its dossier opens (see ensureCountryData in index.html).
.NOTES
  data/app-data.js stays in the repo as the compiled source of truth; re-run this
  script whenever it is regenerated. Byte-exact: values are copied, never re-serialized.
#>
param([string]$Source = (Join-Path $PSScriptRoot '..\data\app-data.js'))
$ErrorActionPreference = 'Stop'

$srcPath = [IO.Path]::GetFullPath($Source)
$dataDir = Split-Path $srcPath
$s = [IO.File]::ReadAllText($srcPath)

Add-Type -TypeDefinition @'
public static class AsjSplit {
  // Index of the brace matching s[start] ('{'), string- and escape-aware. -1 if unbalanced.
  public static int MatchBrace(string s, int start) {
    int depth = 0; bool inStr = false; bool esc = false;
    for (int i = start; i < s.Length; i++) {
      char c = s[i];
      if (inStr) {
        if (esc) esc = false;
        else if (c == '\\') esc = true;
        else if (c == '"') inStr = false;
      } else {
        if (c == '"') inStr = true;
        else if (c == '{') depth++;
        else if (c == '}') { depth--; if (depth == 0) return i; }
      }
    }
    return -1;
  }
}
'@

function Get-ObjectSpan([string]$marker) {
  $i = $s.IndexOf($marker); if ($i -lt 0) { throw "marker not found: $marker" }
  $b = $s.IndexOf('{', $i)
  $e = [AsjSplit]::MatchBrace($s, $b)
  if ($e -lt 0) { throw "unbalanced braces after $marker" }
  @{ assign = $i; start = $b; end = $e }
}

function Split-TopLevelEntries($span) {
  $entries = [ordered]@{}
  $i = $span.start + 1
  while ($i -lt $span.end) {
    while ($i -lt $span.end -and ([char]::IsWhiteSpace($s[$i]) -or $s[$i] -eq ',')) { $i++ }
    if ($i -ge $span.end) { break }
    if ($s[$i] -ne '"') { throw "expected key quote at offset $i, found '$($s[$i])'" }
    $kEnd = $s.IndexOf('"', $i + 1)
    $key = $s.Substring($i + 1, $kEnd - $i - 1)
    $vStart = $s.IndexOf('{', $kEnd)
    $vEnd = [AsjSplit]::MatchBrace($s, $vStart)
    if ($vEnd -lt 0) { throw "unbalanced value for key $key" }
    $entries[$key] = $s.Substring($vStart, $vEnd - $vStart + 1)
    $i = $vEnd + 1
  }
  $entries
}

$detSpan = Get-ObjectSpan 'window.UNITED_AFRICA_DATA.countryDetail ='
$gisSpan = Get-ObjectSpan 'window.UNITED_AFRICA_DATA.countryGis ='
$detE = Split-TopLevelEntries $detSpan
$gisE = Split-TopLevelEntries $gisSpan

$outDir = Join-Path $dataDir 'countries'
New-Item -ItemType Directory -Force $outDir | Out-Null
$utf8 = New-Object Text.UTF8Encoding($false)
$ids = @(@($detE.Keys) + @($gisE.Keys) | Sort-Object -Unique)
foreach ($id in $ids) {
  $parts = @("// $id country chunk - generated by scripts/split-app-data.ps1 from data/app-data.js")
  if ($detE.Contains($id)) { $parts += 'window.UNITED_AFRICA_DATA.countryDetail["' + $id + '"] = ' + $detE[$id] + ';' }
  if ($gisE.Contains($id)) { $parts += 'window.UNITED_AFRICA_DATA.countryGis["' + $id + '"] = ' + $gisE[$id] + ';' }
  [IO.File]::WriteAllText((Join-Path $outDir "$id.js"), (($parts -join "`n") + "`n"), $utf8)
}

# app-core.js: everything except the two big per-country blocks, which become empty
# holders that the chunks mutate (index.html's consts capture these same objects).
$wbIdx = $s.IndexOf('window.UNITED_AFRICA_DATA.worldBankEconomy')
if ($wbIdx -lt 0) { throw 'worldBankEconomy marker missing' }
$core = $s.Substring(0, $detSpan.assign) +
        "window.UNITED_AFRICA_DATA.countryDetail = window.UNITED_AFRICA_DATA.countryDetail || {};`n" +
        "window.UNITED_AFRICA_DATA.countryGis = window.UNITED_AFRICA_DATA.countryGis || {};`n" +
        $s.Substring($wbIdx)
[IO.File]::WriteAllText((Join-Path $dataDir 'app-core.js'), $core, $utf8)

$coreKB = [math]::Round((Get-Item (Join-Path $dataDir 'app-core.js')).Length / 1KB)
Write-Host "[split] app-core.js ${coreKB}KB + $($ids.Count) country chunks in data/countries/"
